### ISSUE TITLE
zlib issues during installation

### ISSUE THREAD

**Issue by JohnnyChen1113** [RabbitBio/RabbitQCPlus#1]
``Hi!

I try to use the RabbitQCPlus on my PacBio HiFi reads QC step. But I cannot solve the zlib-related issues, so I have to reach out to ask for help from you...

1. I installed the gcc 12.1.0, gxx 12.1.0 and zlib 1.2.12, libzlib 1.2.12, zlib-ng 2.0.6 by conda, but it doesn't work. 
2. So, I also tried to use yum install zlib and zlib-devel, but also failed. 
3. And then, I tried soft link or directly copying the zlib.h from where it was installed, but it also doesn't work.

The error msg attached below:
```
g++ -c src/FastxStream.cpp -o obj/FastxStream.o -DVec256 -std=c++11 -I./ -I./common -march=native  -g -O3  -w -fopenmp
In file included from src/FastxStream.cpp:16:
src/FastxStream.h:21:10: fatal error: zlib.h: No such file or directory
   21 | #include <zlib.h>  //support gziped files, functional but inefficient
      |          ^~~~~~~~
compilation terminated.
make: *** [obj/FastxStream.o] Error 1
```
The system I used is centOS 7, Architecture is x86_64. 
If possible, please give me a hand. Thanks a lot!

**Comment by yanlifeng** [comment]
Hi!
This problem may be caused by a different default installation.
The most direct and effective solution is to modify `CXXFLAGS` in the Makefile and manually include the zlib library via `-I`.
