### ISSUE TITLE
使用绝对路径指定输出路径时报错

### ISSUE THREAD

**Issue by imDpeng** [RabbitBio/RabbitQCPlus#2]
使用绝对路径指定输出路径会报错: 
![image](https://user-images.githubusercontent.com/48267340/203458106-8e26e85c-90af-41ab-835d-bc0f095df74e.png)
将执行路径切换到输出目录下时，-o/O直接指定文件名则正常运行
![image](https://user-images.githubusercontent.com/48267340/203458469-909064f3-7d7d-4400-9016-d22aa1b37bb4.png)

**Comment by ZekunYin** [comment]
您好，
感谢使用我们软件。目前这个问题看上去像是路径加了一个前缀，我们尝试一下复现一下问题。您方便的话希望您提供一下更详细的信息，比如操作系统版本，编译器版本，文件规模等，十分感谢！
祝好，
泽坤

**Comment by yanlifeng** [comment]
@imDpeng 
您好，十分感谢您发现的问题，我们已经在最新的提交中修复了这个问题。
祝好，
立峰

**Comment by KristinaGagalova** [comment]
Making this understandable to everyone can help more users to understand.
