### ISSUE TITLE
segmentation fault core dumped

### ISSUE THREAD

**Issue by Rohit-Satyam** [RabbitBio/RabbitQCPlus#5]
Hi @ZekunYin @yanlifeng @LeiHaoa @XiaomingXu1995 

I was trying to use `RabbitQCPlus` as a part of nextflow automated pipeline, but I am observing some issues. The tool runs just fine on the raw fastq files but when I perform adapter trimming using `porechop_abi` it runs fine on few samples but fails for the others

```bash
./tools/RabbitQCPlus/RabbitQCPlus -i 02_adapterTrimming/barcode86_sample_4447.fastq --TGS

now auto detect adapter
Segmentation fault (core dumped)
```

Can you help me with this? I can even share the sample should you like to look into it.
PS: I am running this on workstation and the data is small 75MB so memory shouldn't be an issue. The data before trimming was around 100MB and the tool ran fine. Post trimming only sample with 5MB size ran successfully.

**Comment by Rohit-Satyam** [comment]
`rabbit_qc` ran fine on all samples on which `RabbitQCPlus` failed. So it's not the files with fault.

**Comment by yanlifeng** [comment]
Hi!
Can you provide the data?
Thanks!

**Comment by Rohit-Satyam** [comment]
Kindly provide your email ID.

**Comment by yanlifeng** [comment]
OK! lifeng.yan@mail.sdu.edu.cn

**Comment by Rohit-Satyam** [comment]
You should have received an email from `rohit.satyam@kaust.edu.sa`

**Comment by yanlifeng** [comment]
Thank you very much for identifying the issue and providing the data. We have addressed it in this [commit](https://github.com/RabbitBio/RabbitQCPlus/commit/b03b8f95fc9d6247912abbaa6f7b6a02e17cce9f).
Best wishes.

**Comment by yanlifeng** [comment]
Thank you very much for identifying the issue and providing the data. We have addressed it in this [commit](https://github.com/RabbitBio/RabbitQCPlus/commit/b03b8f95fc9d6247912abbaa6f7b6a02e17cce9f).
Best wishes.
