### ISSUE TITLE
add to bioconda

### ISSUE THREAD

**Issue by jianshu93** [RabbitBio/RabbitQCPlus#6]
Dear RabbitQCPlus team,

I am wondering whether it is time to add RabbitQCPlus to bioconda. I can imagine it will be very popular. I can do it if it it ok with you (e.g. we need to have new release before adding to bioconda).

Thanks,

Jianshu

**Comment by yanlifeng** [comment]
Hi, Jianshu!
I am very sorry for such a late reply.
Thanks for your valuable suggestion, I have added rabbitqcplus to bioconda, you can refer to the README for details on how to use it.
