### ISSUE TITLE
'bitsWanted > 0' failed in 'BitBuffer BitReader

### ISSUE THREAD

**Issue by Hildsley** [RabbitBio/RabbitQCPlus#7]
Dear RabbitQCPlus Team

I used RabbitQCPlus within a script to preprocess my exome seq samples with the following code:

 ~/RabbitQCPlus/RabbitQCPlus -i ../../$filename1 \
				-I ../../$filename2 \
				-w $Threads_use \
				--decAdaForPe \
				--pairmode PE \
				--adapterSeq1 CTGTCTCTTATACACATCT \
				--adapterSeq2 CTGTCTCTTATACACATCT \
				--trim5End \
				--trim3End \
				--trimFront1 20 \
				--trimFront2 20 \
				--trimTail1 5 \
				--trimTail2 5 \
				-o ${Sample_name}_Trimmed_R1.fastq \
				-O ${Sample_name}_Trimmed_R2.fastq

This worked for 14 out of my 15 samples, but produced an error for one of my samples. The error received is listed here below.

./include/BitReader.hpp:346: Assertion 'bitsWanted > 0' failed in 'BitBuffer BitReader<MOST_SIGNIFICANT_BITS_FIRST, BitBuffer>::peek(uint8_t) [with bool MOST_SIGNIFICANT_BITS_FIRST = false; BitBuffer = long unsigned int; uint8_t = unsigned char]'.
./WESIllumina_Script_local_gatkGPU.sh: line 100:  6044 Aborted                 (core dumped) 

When using fastp with similar options on this failed sample, the required process of trimming worked and therefore I suspect the sample input fastq files are fine.

Can you help me with this issue?

**Comment by yanlifeng** [comment]
Thank you for your question!
It seems to be a problem with the parallel decompression engine.
Can you provide data on what went wrong with the run?
It would be very helpful for us to resolve this issue as soon as possible.

**Comment by Hildsley** [comment]
Dear @yanlifeng 

The error code above is all that was printed to the console, and no output files were produced. Other than that, I do not have any additional info or data regarding what went wrong.

I used this exact same script for 14 other samples, sequenced on the same run, but only this single sample produces this error even though I have tried to run it several times in a separate console.

**Comment by yanlifeng** [comment]
Thank you for your reply!
What I meant was can you provide the input file where the error occurs, maybe xx.fastq or xx.fastq.gz.
I tested many input data but did not reproduce the error.
If you can provide that FASTQ input file I'm sure I can solve the problem quickly.

Thanks! Best wishes!

**Comment by Hildsley** [comment]
Yes, Please find the link to the files I used exactly as is for the input.

https://www.dropbox.com/scl/fo/c3g9wjkr60ok1qm8pdeob/ADdVfFv_aBBQBYYo9NugeDE?rlkey=p3xwj1bv0ba5mw9hkxuqs1rv1&st=iwtyk76v&dl=0

**Comment by yanlifeng** [comment]
Thanks for the data!
Sorry for this late reply, I took a holiday last week.
We have fixed the issue in the latest commit.
Best wishes!
