### ISSUE TITLE
Quality plots for hifi reads 

### ISSUE THREAD

**Issue by ewan-harney** [RabbitBio/RabbitQCPlus#8]
Dear RabbitQCPlus team,

When inspecting quality plots of PacBio hifi reads, the plots appear empty, because the y-axis is limited to phred 40. But hifi reads have phred quality scores that range from 0 to 93. One can see what the result is at any given position by mousing over the position in the read (along the x-axis), but it would be useful to be able to see these results in the plots.

As far as I can see there is no way to change this via command line parameters, is this something that could be included in a future update?

Many thanks,

Ewan

**Comment by yanlifeng** [comment]
Dear Ewan,

Thank you for your feedback. This issue has been resolved in our latest update: in long read (--TGS) mode, the HTML report y-axis is now adaptive rather than fixed at 40.

Best,
Lifeng

**Comment by ewan-harney** [comment]
Dear Lifeng,

Thanks for your quick reply, that's great to know that the most recent version features a dynamic y-axis.

I've just checked my version, and it shows as 2.1.0. However, I have run into some problems trying to update it. Although updating or creating a new environment suggests that conda is installing rabbitqcplus-2.2.9, that doesn't appear to be the case: --version continues to show 2.1.0, and html reports still have the y-axis fixed, so I wonder if there is an issue with the version on bioconda? I've tried on a couple of systems and have had the same problem.

Thanks again for your help,
Best,
Ewan

**Comment by yanlifeng** [comment]
Dear Ewan,

Thanks for letting us know. We’ll work on integrating the recent updates and releasing a new version to Bioconda as soon as possible.

In the meantime, you can manually compile the latest source code for temporary use (see README: From source for instructions).

Best,
Lifeng

**Comment by yanlifeng** [comment]
Dear Ewan,

We have committed the latest code to bioconda, the latest version is 2.3.0.
Please contact me again if you have any questions.

Best,
Lifeng

**Comment by ewan-harney** [comment]
Dear Lifeng,
Many thanks for getting the update on bioconda, that's working great now.
Best wishes,
Ewan
